### ISSUE TITLE
z-index of rendered maps

### ISSUE THREAD

**Issue by lef-est** [hkgnp/logseq-osmmaps-plugin#7]
Can you make it lower so that it doesn't cover top toolbar's plugin menu and overflow menu? :)

**Comment by benjypng** [comment]
Hmm, do you have a screenshot?
________________________________
From: lef-est ***@***.***>
Sent: Friday, March 31, 2023 7:40 PM
To: hkgnp/logseq-osmmaps-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-osmmaps-plugin] z-index of rendered maps (Issue #7)


Can you make it lower so that it doesn't cover top toolbar's plugin menu and overflow menu? :)

**Comment by lef-est** [comment]
Sure!
![image](https://user-images.githubusercontent.com/9643637/229263499-2aaf8c50-04c9-4d71-952c-e4e64d0db5e5.png)
![image](https://user-images.githubusercontent.com/9643637/229263508-5bb03d89-8b73-4759-a595-f999293fdaaa.png)

My custom CSS didn't change the z-index of either top bar or this plugin.


This might help you pintpoint the element (notice that the *un*rendered tiles do not cover the menu):
![image](https://user-images.githubusercontent.com/9643637/229263546-88a12ef9-bf50-4900-997b-b1914f7b1dd2.png)

**Comment by benjypng** [comment]
Fixed in latest version.

**Comment by lef-est** [comment]
🙏 Thanks!
